service: development-ml-lambda-concurrency-spike

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  Dummy:
    handler: src/lambda/dummy.handle
    memorySize: 128
    timeout: 30
    events:
      - externalSNS: 'development-ml-lambda-trigger'
    environment:
      PROPONOJS_APPLICATION_NAME: 'concurrency_spike'
      PROPONOJS_QUEUE_REGION: ${env:PROPONOJS_QUEUE_REGION}
      PROPONOJS_QUEUE_SUFFIX: ${env:PROPONOJS_QUEUE_SUFFIX}
      PROPONOJS_AWS_SECRET_KEY: ${env:PROPONOJS_AWS_SECRET_KEY}
      PROPONOJS_AWS_ACCESS_KEY_ID: ${env:PROPONOJS_AWS_ACCESS_KEY_ID}

